// apps/web/components/Loading.vue
<template>
  <div>
    <span class="sr-only">Loading</span>
    <div class="flex items-center justify-center gap-4">
      <span className="loading loading-bars loading-xs text-info"></span>
      <span className="loading loading-bars loading-sm text-warning"></span>
      <span className="loading loading-bars loading-md text-success"></span>
      <span className="loading loading-bars loading-lg text-error"></span>
    </div>
  </div>
</template>

// apps/web/src/components/Loading.tsx
export default function Loading() {
  return (
    <div className="flex h-screen justify-center items-center">
      <div className="flex gap-4">
        <span className="loading loading-bars loading-xs text-info"></span>
        <span className="loading loading-bars loading-sm text-success"></span>
        <span className="loading loading-bars loading-md text-warning"></span>
        <span className="loading loading-bars loading-lg text-error"></span>
      </div>
    </div>
  )
}
